language: php

php:
  - 5.3
  - 5.4

env:
  - CAKE_VERSION=master
  - CAKE_VERSION=2.4

before_script:
  - git clone --depth 1 --branch $CAKE_VERSION git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp
  - rm -R app
  - git clone --depth 1 git://github.com/dereuromark/tools-app app && cd app && git checkout master
  - cd ..
  - cp -R ../tools plugins/Tools
  - sh -c "mysql -e 'CREATE DATABASE cakephp_test;'"
  - mkdir ./app/tmp
  - mkdir ./app/tmp/logs
  - mkdir ./app/tmp/sessions
  - mkdir ./app/tmp/tests
  - mkdir ./app/tmp/cache
  - mkdir ./app/tmp/cache/persistent
  - mkdir ./app/tmp/cache/models
  - chmod -R 0777 ./app/tmp
  - echo "<?php
    class DATABASE_CONFIG {
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'database' => 'cakephp_test',
      'host' => '0.0.0.0',
      'login' => 'travis',
      'host' => '',
      'persistent' => false,
    );
    }" > app/Config/database.php
  - cd app
script:
  - ../lib/Cake/Console/cake test Tools AllTools

notifications:
  email: false