language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  global:
    - REPO_NAME=cakephp-tools
    - PLUGIN_NAME=Tools
    - DB=mysql
  matrix:
    - DB=mysql CAKE_VERSION=master
    - DB=mysql CAKE_VERSION=2.6

matrix:
  include:
    - php: 5.4
      env:
        - CAKE_VERSION=master
        - COVERALLS=1
  fast_finish: true

before_script:
  - composer global require 'phpunit/phpunit=3.7.33'
  - git clone https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - ../travis/before_script.sh
  - cd ../cakephp/app
  - ln -s ~/.composer/vendor/phpunit/phpunit/PHPUnit Vendor/PHPUnit
  - echo "Configure::write('Security.salt', 'AxcG93b0qyJfIxfs2guVoUubWwvniR2G0FgaC9mi');" >> Config/bootstrap.php
  - echo "Configure::write('Security.cipherSeed', '16659201697453542496749683615');" >> Config/bootstrap.php
  - echo "<?php App::uses('MyModel', 'Tools.Model'); class AppModel extends MyModel {}" > Model/AppModel.php
  - echo "<?php App::uses('MyController', 'Tools.Controller'); class AppController extends MyController {}" > Controller/AppController.php
  - echo "<?php App::uses('BaseEmailConfig', 'Tools.Config'); class EmailConfig extends BaseEmailConfig {}" > Config/email.php
  - echo "Configure::write('Config.adminEmail', 'example@example.org');" >> Config/bootstrap.php
  - cd ..
  - cp ../cakephp-tools/phpunit.xml app/

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false